apiVersion: v1
kind: Pod
metadata:
  name: sfr-pod-amrita-saha
  namespace: sfr-ns-amrita-saha
spec:
  restartPolicy: OnFailure
  volumes:
    - name: sfr-home-pv-amrita-saha
      persistentVolumeClaim:
        claimName: sfr-home-pvc-amrita-saha
  containers:
    - name: nmn-drop
      image: "gcr.io/salesforce-research-internal/nmn-drop:latest"
      command: ["sleep", "infinity"]
      resources:
        limits:
              nvidia.com/gpu: 1
      volumeMounts:
        - name: sfr-home-pv-amrita-saha
          mountPath: "/export/home"
  tolerations:
  - key: "gpu_num"
    operator: "Equal"
    value: "2"
    effect: "NoSchedule"
